name: trajectory_analysis_tools
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.6"
- numpy
- scipy
- networkx
- matplotlib
- loren_frank_data_processing
- replay_trajectory_classification
- ripple_detection
- xarray
- pandas
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
